[task_01] done task_01
brstu/TMAU-2024 pull request #13
Opened 2024-09-22 11:10 UTC by XD-cods

2024-09-22 14:52 UTC, gleb7499 commented
You've done a great job redoing my code, well done🤌

2024-09-26 04:57 UTC, NogameNo-life requested changes

2024-09-26 04:57 UTC, NogameNo-life commented on trunk/as0006413/task_01/doc/readme.md
> +![alt text](image-1.png)
В markdown можно писать формулы как в Latex

2024-09-28 06:13 UTC, NogameNo-life approved these changes

2024-09-28 06:38 UTC, merged