[task_01] Add solution
brstu/TMAU-2024 pull request #61
Opened 2024-10-19 09:39 UTC by Ritkas33395553

2024-10-26 07:39 UTC, NogameNo-life requested changes
Нужно переименовать "Cmakelist.txt" на "CMakeLists.txt"

2024-10-26 07:39 UTC, NogameNo-life commented on trunk/as0006320/task_01/src/Cmakelist.txt
> +add_executable(task001 lab1.cpp) # создание исполняемого файла
```suggestion
project (task001_6320)

add_executable(${PROJECT_NAME} lab1.cpp) # создание исполняемого файла
```

2024-11-01 13:00 UTC, Ritkas33395553 commented
Исправила

2024-11-04 06:10 UTC, NogameNo-life approved these changes

2024-11-04 06:11 UTC, merged